import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { RankingList } from "@/components/RankingList";
import { SiteHeader } from "@/components/SiteHeader";
import { StructuredData } from "@/components/StructuredData";
import { categoryFromRouteSlug, categoryRouteSlug, localizedPath, pick, rankingFromRouteSlug, rankingRouteSlug } from "@/lib/i18n";
import { requireLocale } from "@/lib/locale-page";
import { absoluteUrl, averageDataCompleteness, countUniqueInsights, evaluateSeoPage, getSeoPageDefinition } from "@/lib/seo";
import { getCatalog } from "@/lib/static-data";

type Props = { params: Promise<{ locale: string; attribute: string; category: string }> };
export function generateStaticParams() { return (["de-DE", "en-US"] as const).flatMap((locale) => getCatalog(locale).rankingPages.map((page) => ({ locale: locale === "de-DE" ? "de" : "en-us", attribute: rankingRouteSlug(page.attribute, locale), category: categoryRouteSlug(page.category, locale) }))); }

function resolve(values: { locale: string; attribute: string; category: string }) { const locale = requireLocale(values.locale); const catalog = getCatalog(locale); const attribute = rankingFromRouteSlug(values.attribute, locale); const category = categoryFromRouteSlug(values.category, locale); const ranking = attribute && category ? catalog.getRanking(attribute, category) : null; return { locale, catalog, ranking, attribute, category }; }

export async function generateMetadata({ params }: Props): Promise<Metadata> { const values = await params; const { locale, catalog, ranking } = resolve(values); if (!ranking) return {}; const items = catalog.rankedProducts(ranking.category, ranking.sortScore); const canonical = localizedPath(locale, `/best/${values.attribute}/${values.category}`); const decision = evaluateSeoPage(getSeoPageDefinition(canonical), { resultCount: items.length, dataCompleteness: averageDataCompleteness(items), uniqueInsightCount: countUniqueInsights(items), title: ranking.title, h1: ranking.title }); const counterpartLocale = locale === "de-DE" ? "en-US" : "de-DE"; const counterpart = localizedPath(counterpartLocale, `/best/${rankingRouteSlug(ranking.attribute, counterpartLocale)}/${categoryRouteSlug(ranking.category, counterpartLocale)}`); return { title: `${ranking.title} - Food Decision Engine`, description: ranking.intro, alternates: { canonical, languages: { [locale]: canonical, [counterpartLocale]: counterpart, "x-default": localizedPath("de-DE", `/best/${rankingRouteSlug(ranking.attribute, "de-DE")}/${categoryRouteSlug(ranking.category, "de-DE")}`) } }, robots: { index: decision.indexable, follow: true } }; }

export default async function RankingPage({ params }: Props) { const values = await params; const { locale, catalog, ranking } = resolve(values); if (!ranking) notFound(); const path = (value = "/") => localizedPath(locale, value); const items = catalog.rankedProducts(ranking.category, ranking.sortScore); const category = catalog.getCategory(ranking.category); const insights = { completeness: Math.round(averageDataCompleteness(items) * 100), products: items.length };
  return <main><StructuredData data={{ "@context": "https://schema.org", "@type": "ItemList", name: ranking.title, inLanguage: locale, url: absoluteUrl(path(`/best/${values.attribute}/${values.category}`)), numberOfItems: items.length, itemListElement: items.map((product, index) => ({ "@type": "ListItem", position: index + 1, name: product.name, url: absoluteUrl(path(`/product/${product.slug}`)) })) }} /><SiteHeader locale={locale} /><nav className="breadcrumb" aria-label="Breadcrumb"><Link href={path()}>{pick(locale, "Start", "Home")}</Link><span>/</span><Link href={path(`/category/${values.category}`)}>{category?.label}</Link><span>/</span><span>{pick(locale, "Ranking", "Ranking")}</span></nav><section className="subpage-hero"><p className="eyebrow">{pick(locale, "Datenbasiertes Ranking", "Data-based ranking")}</p><h1>{ranking.title}</h1><p>{ranking.intro}</p></section><section className="ranking-context"><div><p className="eyebrow">{pick(locale, "So wird sortiert", "How it is sorted")}</p><h2>{pick(locale, "Vergleichbar und transparent", "Comparable and transparent")}</h2></div><p>{pick(locale, `Aktuell werden ${insights.products} geeignete Produkte anhand desselben Kriteriums verglichen. Datenvollständigkeit: ${insights.completeness} %.`, `${insights.products} eligible products are currently compared using the same criterion. Data completeness: ${insights.completeness}%.`)}</p></section><section className="section">{items.length ? <RankingList locale={locale} products={items} /> : <div className="empty-state"><h2>{pick(locale, "Noch kein belastbares Ranking", "No reliable ranking yet")}</h2><p>{pick(locale, "Diese Seite bleibt bis zu ausreichender Produkt- und Datenabdeckung aus dem Suchindex.", "This page stays out of search until product and data coverage are sufficient.")}</p></div>}</section></main>;
}
